export function uselessWebButton(button, popup) {
	// var buttonElement = button
	// var popupElement = popup
	// var initialClick = false
	// var randomRange = 7

	var sitesList = [
		"https://www.adultswim.com/etcetera/elastic-man/app.html",
		"https://www.adultswim.com/etcetera/zoom/",
		"https://www.adultswim.com/etcetera/extras/index.php?id=3c",
		"https://www.adultswim.com/etcetera/choir/",
		"https://www.adultswim.com/etcetera/smash-n-dab/",
		"https://longdogechallenge.com/",
		"http://heeeeeeeey.com/",
		"http://corndog.io/",
		"https://puginarug.com",
		"https://alwaysjudgeabookbyitscover.com",
		"https://thatsthefinger.com/",
		"https://cant-not-tweet-this.com/",
		"http://eelslap.com/",
		"http://www.staggeringbeauty.com/",
		"http://burymewithmymoney.com/",
		"https://smashthewalls.com/",
		"https://jacksonpollock.org/",
		"http://endless.horse/",
		"https://www.trypap.com/",
		"http://www.republiquedesmangues.fr/",
		"http://www.movenowthinklater.com/",
		"http://www.partridgegetslucky.com/",
		"http://www.rrrgggbbb.com/",
		"http://www.koalastothemax.com/",
		"http://www.everydayim.com/",
		"http://randomcolour.com/",
		"http://cat-bounce.com/",
		"http://chrismckenzie.com/",
		"https://thezen.zone/",
		"http://hasthelargehadroncolliderdestroyedtheworldyet.com/",
		"http://ninjaflex.com/",
		"http://ihasabucket.com/",
		"http://corndogoncorndog.com/",
		"http://www.hackertyper.com/",
		"http://imaninja.com/",
		"http://drawing.garden/",
		"http://www.ismycomputeron.com/",
		"http://www.nullingthevoid.com/",
		"https://boringboringboring.com/",
		"http://www.yesnoif.com/",
		"http://potatoortomato.com/",
		"http://iamawesome.com/",
		"https://strobe.cool/",
		"http://thisisnotajumpscare.com/",
		"http://crouton.net/",
		//"http://www.wutdafuk.com/",
		"http://unicodesnowmanforyou.com/",
		"http://chillestmonkey.com/",
		"http://scroll-o-meter.club/",
		"http://www.crossdivisions.com/",
		"http://tencents.info/",
		"https://boringboringboring.com/",
		"http://www.patience-is-a-virtue.org/",
		"http://pixelsfighting.com/",
		"http://isitwhite.com/",
		"https://existentialcrisis.com/",
		"http://onemillionlols.com/",
		"http://chihuahuaspin.com/",
		"https://popcat.click/",
		"http://www.blankwindows.com/",
		"http://tunnelsnakes.com/",
		"http://www.trashloop.com/",
		"http://spaceis.cool/",
		"http://www.donothingfor2minutes.com/",
		"http://buildshruggie.com/",
		"http://buzzybuzz.biz/",
		"http://yeahlemons.com/",
		"http://wowenwilsonquiz.com",
		"https://thepigeon.org/",
		"http://notdayoftheweek.com/",
		"http://www.amialright.com/",
		"http://nooooooooooooooo.com/",
		"https://greatbignothing.com/",
		"https://dadlaughbutton.com/",
		"https://www.bouncingdvdlogo.com/",
		"https://remoji.com/",
		"http://papertoilet.com/",
		"https://loopedforinfinity.com/",
		"https://erdetfredag.dk",
		"https://erdetmandag.dk/",
		"http://erdettirsdag.dk/",
		"https://erdetonsdag.dk/",
		"https://erdettorsdag.dk/",
		'https://erdetlørdag.dk/',
		"http://www.xn--erdetsndag-5cb.dk/",
		"https://procatinator.com/",
		"https://findtheinvisiblecow.com/",
		"https://trypap.com/",
		"https://whatsmystarbucksname.com/",
		"https://chickensalad303.github.io/stars_homepage/mario_the_ma.jpg",
		"https://thispersondoesnotexist.com/",
		"https://scanwiches.com/",
		"https://neal.fun/paper/",
		"https://zoomquilt.org/",
		"https://arkadia.xyz/",
		"https://zoomquilt2.com/",
		"https://neal.fun/deep-sea/",
		"https://www.kamogo.com/22",
		"https://www.fishcam.com/",
		"https://www.theuncomfortable.com/",
		"http://www.googolplexwrittenout.com/",
		"http://www.byronknoll.com/earth.html",
		
	]
    var site =  sitesList[Math.floor(Math.random() * sitesList.length)] // get random from 

    return site
}

